### ISSUE TITLE
Change admin site header on report page

### ISSUE THREAD

**Issue by anmolbk** [simplyopen-it/django-admin-reports#29]
Report page shows the default admin site header ("Django administration"). I have changed my admin app's site header in url.py:

`admin.site.site_header = "My admin header"`

How to change the one shown on report page? I tried changing it in `AdminReportSite` similarly, but did not work. Thanks.

**Comment by oberix** [comment]
Sorry, at the moment the `AdminReportSite` does not extend `django.contrib.admin.AdminReport` and thus it does not follow the admin header. I fear you'll have to extend the template `admin/report.html` and overwrite the blocks title and branding.

**Comment by anmolbk** [comment]
Ok, thanks @oberix!
