### ISSUE TITLE
ValuesQuerySet removed in Django 1.9

### ISSUE THREAD

**Issue by k8n** [simplyopen-it/django-admin-reports#5]
ValuesQuerySet has been removed in Django 1.9 ([release notes](https://docs.djangoproject.com/en/1.9/releases/1.9/#miscellaneous)).

Dependency introduced in 2e42180e4af506442fc491515e16f51a40ce29c4

**Comment by oberix** [comment]
Thanks for pointing this out. 28524c6aa381fe3019ada43f14b5477e465ea424 should fix the issue while maintaining compatibility with django 1.8.
