### ISSUE TITLE
Autodiscover still not working

### ISSUE THREAD

**Issue by SoulRaven** [simplyopen-it/django-admin-reports#6]
i have to to add inside the project settings url:
`url(r'^api-auth/', include('rest_framework.urls', namespace="rest_framework")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include(admin_reports.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),`

but is not working, i get 404 "The current URL, admin/trackDevices/devicessessionhistoryreport, didn't match any of these."

in my app folder exista a reports.py file with the basic example from you git tutorial.

any ideea way?

**Comment by oberix** [comment]
My mistake, the URL should have a trailing slash '/', so please try with admin/trackDevices/devicessessionhistoryreport/

This is how the model's admins URLs are, I will update the README.

**Comment by SoulRaven** [comment]
still not working, the same error:
The current URL, admin/trackDevices/devicessessionhistoryreport/, didn't match any of these.

**Comment by oberix** [comment]
Can you tell me the name of your django app? Is it exactly `trackDevices`?
Also is the report class called exactly `DevicesSessionHistoryReport`? 

In the README I assumed PEP8 naming conventions.

Finally (sorry if it's silly), is `adin_reports` in your site's `settings.INSTALLED_APPS`?

**Comment by SoulRaven** [comment]
no, in settings.INSTALLED_APPS in nothing related to admin_reports
and yes, the name of the app is trackDevices, and the class is DevicesSessionHistoryReport

**Comment by oberix** [comment]
Ok then. `admin_reports` must be in `INSTALLED_APPS` for the reports url to be registeres.

Maybe I should have mentioned that in the README. Thanks for pointing this out.

**Comment by SoulRaven** [comment]
Same problem,
The current URL, admin/trackDevices/myreport, didn't match any of these.

`url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include(admin_reports.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),`

and inside settings.INSTALLED_APPS
`'company',
    'userProfile',
    'subscription',
    'suit',
    'admin_reports',`

**Comment by SoulRaven** [comment]
ok, now is working, the admin_reports must be pus inside the INSTALLED_APPS after the 'django.contrib.admin',

**Comment by SoulRaven** [comment]
also, what it means "Negative indexing is not supported."

https://dpaste.de/UvYG
https://dpaste.de/8Jim

**Comment by SoulRaven** [comment]
Ok, problem came from the attribute has_totals = True
now the problem is that with `values("device__licensePlate").annotate(` i get only the  device__licensePlate all the fields are empty

**Comment by oberix** [comment]
> Ok, problem came from the attribute has_totals = True

You are right, `has_total` is broken for querysets since they do not support negative indexing (you can't do `qs[-1]` to select the last element of a queryset).

> now the problem is that with values("device__licensePlate").annotate( i get only the device__licensePlate all the fields are empty

I'd need more details, try to check what's the output of your query. Also did you configure the `fields` attribure accordingly (or simply remove it, the report should show all the fileds).

**Comment by SoulRaven** [comment]
i manage to resolve all the problems, except has_total, and this is really important, and also now i try to find out if is possibile to add a link to a separate view to display graphs

Can you make any modification to make the has_total to work again?

**Comment by oberix** [comment]
Perfect, will close this issue and open another one about `has_totals` not working with querysets.

About graphs, this is something I would be happy to implement but I'm quite reluctant in forcing dependencies to third party libraries. Any suggestion is welcome though.
